### ISSUE TITLE
Redis connection name in docs

### ISSUE THREAD

**Issue by brendt** [spatie/laravel-email-campaigns#13]
The docs state:

> Install and configure redis
> Most e-mail providers have a limit on how many mails you can send within a given amount of time. To throttle mails, this package uses Redis. Make sure that is available on your system. You must specify a valid redis connection name in the throttling.redis_connection_name key.

Could we mention the default name here? I'm actually unsure about what it is, my guess is `redis`, though it's not listed under `database.connections`, it's configured as `database.redis`, which is Laravel's default config. 

I guess Laravel's config is just a little unclear about this without reading its docs, so a little more clarification in our docs couldn't hurt.

**Comment by freekmurze** [comment]
Fixed.
