### ISSUE TITLE
[Proposal] List-Unsubscribe Header

### ISSUE THREAD

**Issue by davidpiesse** [spatie/laravel-email-campaigns#29]
New feature for this package - Add a List-Unsubscribe header

It's common / expected that any campaign email will have an unsubscribe link in the email.
In addition you should also be using the header 'List-Unsubscribe'.

This is what Gmail and Mail on iOS use to show you that one click Unsubscribe link/button.
More info [here](https://litmus.com/blog/the-ultimate-guide-to-list-unsubscribe).

To add a header is possible (https://laravel.com/docs/6.x/mail#customizing-the-swiftmailer-message) and it would work with just a url to the unsubscribe link which already exists.

However the one puzzle piece missing is incoming emails to unsubscribe (what majority fo the email clients use).

Laravel Mailbox (https://github.com/beyondcode/laravel-mailbox) by Marcel would be idea for catching these emails; maybe in a format of unsubscribe-{{uuid}}@domain.com

It may also require a boolean config value to 'enable_unsubscribe_header'.

Is this something of interest?
😺

**Comment by freekmurze** [comment]
This is certainly of interest and I'd accept a PR that adds this in a clean way. 👍 Make sure it is tested and documented.

I'm not certain, because of the big dependency on laravel-mailbox, if I'd put that code in this package, or create a separate add on package.

**Comment by freekmurze** [comment]
We'll continue this in #34
