### ISSUE TITLE
[Proposal] Add Custom Email Config.

### ISSUE THREAD

**Issue by ManojKiranA** [spatie/laravel-email-campaigns#44]
It will be helpful if there is custom email config for the email Campaign.

For Example.

Many of the Mass Mailers service 

- Mailchimp https://mailchimp.com/
- Sendinblue https://www.sendinblue.com
- Mailerlite https://www.mailerlite.com

All above services are providing the Minimum number of emails as free for basic startup users right now.

So to make use of that we must have some dedicated config in Package. 

Something like below,

```
'serviceproviders' => [

        'Mailchimp' => [
            //config of Mailchimp
        ],
        'Sendinblue' => [
            //config of Sendinblue
        ],
        'Mailerlite' => [
            //config of Mailerlite
        ],
        //more service providers
    ],
```

And While sending

```
Campaign::create()
    ->subject('test')
    ->content($html)
    ->trackOpens()
    ->trackClicks()
    ->to($emailList)
    ->sendUsingProvider('Mailchimp');
```

**Comment by freekmurze** [comment]
I don't need this myself, so I'm not going to invest time in it. I hope Laravel itselfs has multiple mail channels support in the future.
