### ISSUE TITLE
[Small feature request] Option to turn List-Unsubscribe headers off

### ISSUE THREAD

**Issue by connecteev** [spatie/laravel-email-campaigns#51]
@davidpiesse has been kind enough to add [List-Unsubscribe headers](https://github.com/spatie/laravel-email-campaigns/pull/36/files) to every outgoing email:

Documented here:
https://docs.spatie.be/laravel-email-campaigns/v1/working-with-lists/unsubscribing-from-a-list/#unsubscribing-using-an-email-client

While I would want to use this functionality, I also see wanting to turn this off for specific email campaigns. Can we make this configurable? The default can be on or off, but it would be nice to be able to turn these off when sending emails.

**Comment by freekmurze** [comment]
Why would you want to turn this off?

**Comment by connecteev** [comment]
I'd probably want it turned off to not make it super easy to unsubscribe (Don Norman's principle of visibility....the more visible a feature is, the more likely it will get used)

**Comment by freekmurze** [comment]
In the context of email campaigns, I feel unsubscribing should be as easy as possible.
