### ISSUE TITLE
[Small feature request] Allow user to resubscribe on the unsubscribe page

### ISSUE THREAD

**Issue by connecteev** [spatie/laravel-email-campaigns#52]
A lot of sites now allow you to re-subscribe from the unsubscribe page, to re-capture potential lost subscribers. 

One example of this (using my email)
- https://clarity.fm/unsubscribe?e=w&u=5f9465ad-b3a4-44d5-8674-fb06256617cb

Other examples that do this:
[http://growthhackingidea.com](https://prnt.sc/poo5ry)
[ifonly.com](https://prnt.sc/poo5wp)

I think a simple extension of the [::unsubscribeUrl](https://docs.spatie.be/laravel-email-campaigns/v1/working-with-campaigns/creating-a-campaign/#setting-the-content-and-using-placeholders) to offer a ::resubscribeUrl:: (where both are linked together, like on clarity.fm) would be ideal, and would allow you to customize the landing page content to get the user to re-join and change their mind.

**Comment by freekmurze** [comment]
Makes sense, I’ll add this

**Comment by connecteev** [comment]
Thanks @freekmurze

**Comment by freekmurze** [comment]
Probably this package is not the right place as it does not have a subscribe controller. I think care of this in the MailCoach app I'm currenlty building (which uses this package under the hood)

**Comment by connecteev** [comment]
Will MailCoach be open sourced or be paid? If it's not going to be open sourced would it be possible to have resubscribe functionality in an example app? Thanks..

**Comment by freekmurze** [comment]
> Will MailCoach be open sourced or be paid?

Still undecided about that.
