### ISSUE TITLE
[Feature Request] Customize links for Click Tracking

### ISSUE THREAD

**Issue by connecteev** [spatie/laravel-email-campaigns#56]
Based on the documentation for [click tracking](https://docs.spatie.be/laravel-email-campaigns/v1/working-with-campaigns/tracking-clicks/):
```
a link with href https://spatie.be will be replaced with https://yourapp.com/email-campaigns/track-clicks/<campaign-link-uuid>/<subscriber-uuid>?redirect=https://spatie.be
```
The URL may dissuade users from clicking on any links in email campaigns that are sent. I propose that we:
- change the URL to replace "track-clicks" with "link" https:// yourapp.com/email-campaigns/link/<campaign-link-uuid\>/\<subscriber-uuid\>\?redirect=https:// spatie.be
- have a configurable option to obfuscate the URL, like:
https:// yourapp.com/email-campaigns/link/<overall-uuid\>
which encapsulates \<campaign-link-uuid>,  \<subscriber-uuid> and redirect URL into one <overall-uuid>, so that if the sender wants to mask the details, like of redirect url, they can do that.

**Comment by freekmurze** [comment]
I don’t see why users could be dissuaded by that redirect parameter.

**Comment by connecteev** [comment]
You're right, they could be by "track-clicks" in the url...maybe we could change that.

The redirect url obfuscation would just provide more control - it's a nice-to-have.

**Comment by freekmurze** [comment]
I'm going to leave it like it is for now.

**Comment by connecteev** [comment]
I do think that "track-clicks" would turn off privacy-conscious people from clicking...could hurt CTRs...

**Comment by freekmurze** [comment]
You can turn off track linking on a campaign basis.

**Comment by connecteev** [comment]
Right...I do want to track clicks in all my campaigns...would you be open to a PR to change the URL from "track-clicks" to "link"? I think I will be able to manage that if you're game.

**Comment by freekmurze** [comment]
Ok, go ahead 👍
