### ISSUE TITLE
Track deliveries, bounces, complaints when sending email with Amazon SES

### ISSUE THREAD

**Issue by connecteev** [spatie/laravel-email-campaigns#58]
Track deliveries, bounces, complaints when sending email with Amazon SES. SES is a great option for sending emails because the price and domain authority is unbeatable.

In addition to opens, clicks and unsubscribe tracking, track:
- deliveries - % of mail successfully delivered
- bounces - % bad email (auto-update the bounced email's subscriber status so we dont email them in future campaigns)
- complaints - % reported as spam (auto-update the reporter email's subscriber status so we dont email them in future campaigns)

Sendy does this: https://prnt.sc/poxlnk 
It keeps lists clean as bounces, complaints and unsubscribes are automatically handled in real time once a newsletter is sent, so there is no need for any manual post campaign cleanups.

The following packages seem to have this functionality, it would be great to roll that into this package
- https://github.com/oliveready7/laravel-ses
- https://github.com/SwissWeb/interspire-aws-bounce
- https://github.com/archintel-developer/laravel-ses

**Comment by freekmurze** [comment]
These package seem to set up a custom mailer. I wonder if we could get info around bounces, complaints, etc... via the SES API.

**Comment by connecteev** [comment]
I don't know what's easier, but from some searching
```
https://docs.aws.amazon.com/ses/latest/APIReference/API_SendEmail.html
https://docs.aws.amazon.com/ses/latest/APIReference/API_BouncedRecipientInfo.html
https://docs.aws.amazon.com/ses/latest/APIReference/API_SetIdentityFeedbackForwardingEnabled.html
```

**Comment by freekmurze** [comment]
Meanwhile we're implementing this in a separate package.

**Comment by connecteev** [comment]
@freekmurze sounds good....though I'm curious why it's not integrated into this one...seems like a good place to put it..

**Comment by freekmurze** [comment]
I moved to a separate package to avoid having email service provider specific code in laravel-email-campaigns. i like keep this package a bit agnostic.

**Comment by connecteev** [comment]
@freekmurze makes sense, thank you. Will that package be freely available / released anytime soon?

**Comment by freekmurze** [comment]
We're still a bit undecided on that.
