### ISSUE TITLE
[Feature request] Allow different queues for different types of emails

### ISSUE THREAD

**Issue by connecteev** [spatie/laravel-email-campaigns#67]
(Imho this request is of lower utility compared to say, #58, but logging the idea here anyway)

The package lets you [configure different Redis queues](https://docs.spatie.be/laravel-email-campaigns/v1/installation-setup/#publish-the-config-file
) for different jobs. This is really thoughtful.

I am wondering if it would be possible to extend this to allow configuring different queues for different types of emails - for example, welcome email, digest email, order confirmation email, etc. These would have to be user-defined in some way, and if left unspecified, all emails would default to one queue as they do today.

This would help you monitor and scale different types of emails separately.

**Comment by freekmurze** [comment]
Feel free to PR a concrete implemention for this to the package.
