### ISSUE TITLE
Support for transactional emails?

### ISSUE THREAD

**Issue by connecteev** [spatie/laravel-email-campaigns#69]
Is there a plan to add support for transactional emails?
I am currently using this package, which works great for open/click tracking of transactional emails (it happens to also have the ability to listen to SNS notifications for delivered/reported emails, and has a nice [admin panel interface](https://prnt.sc/pqfurc) to see your sent emails, opens, clicks etc.)
https://github.com/jdavidbakr/mail-tracker

But I'm only inquiring about the transactional emails when the user takes an action (signs up, places an order, signs up for a blog etc), so that you dont have to create a campaign / email list / subscription to send an email. It would be good for everything to be in this package...so there's a unified way to track sends/opens/clicks (and possibly delivered/reported emails), all in one place. Are there plans to do this?

**Comment by freekmurze** [comment]
Currently I’m only focusing on mass mailing.
